services:
  api: &main_app
    build:
      context: .
      dockerfile: ./Dockerfile
    image: pillowrss:${PILLOWRSS_VERSION:-latest}
    restart: always
    env_file:
      - path: .env
        required: false
    environment:
      PILLOWRSS_HOST: 0.0.0.0
      PILLOWRSS_DB_FILE: /db_data/db.sqlite3
    volumes:
      - pillowrss-db-data:/db_data/



volumes:
  pillowrss-db-data:
    name: pillowrss-db-data
